name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang
        run: |
          wget -q https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_18.3-1~ubuntu~xenial_amd64.deb
          sudo apt install --allow-downgrades ./esl-erlang_18.3-1~ubuntu~xenial_amd64.deb
      - name: Build with Rebar
        run: |
          ./rebar get-deps
          ./rebar compile
          ./rebar eunit
